@startuml
start
:Показать список задач;
if (Создать новую задачу?) then (да)
  :Запросить данные задачи;
  :Создать задачу;
  :Уведомить наблюдателей;
elseif (Редактировать?) then (да)
  :Выбрать задачу;
  :Редактировать задачу;
  :Уведомить наблюдателей;
elseif (Удалить?) then (да)
  :Выбрать задачу;
  :Удалить задачу;
  :Уведомить наблюдателей;
endif
stop
@enduml
