@startuml
start

:Пользователь выбирает действие;
if (Действие?) then (Кормить)
  :Дать еду;
  :Обновить уровень голода;
elseif (Играть)
  :Начать игру;
  :Обновить уровень счастья;
elseif (Уложить спать)
  :Уложить питомца;
  :Обновить уровень энергии;
elseif (Чистить)
  :Очистить питомца;
  :Обновить уровень здоровья;
endif

:Проверить состояние;
if (Нужны уведомления?) then (да)
  :Отправить уведомление (голод, здоровье, счастье);
endif

stop

@enduml